config/routes.rb
Rails.application.routes.draw do
  root to: "plants#index"

  resources :production_steps

  resources :production_cards

  resources :locations do
    get :autocomplete_location_name, on: :collection
  end

  resources :vendors do
    get :autocomplete_vendor_name, on: :collection
  end

  resources :seeds

  resources :plants do
    get :autocomplete_plant_name, on: :collection
  end

  resources :pollinators do
    get :autocomplete_pollinator_name, on: :collection
    member do
      post 'associate'
    end
  end

  resources :common_names

  resources :species

  resources :genus

  resources :families do
    get :autocomplete_family_name, on: :collection
  end

  resources :thermometers

end

app/models/production_card.rb
class ProductionCard < ActiveRecord::Base
  
  validates :plant_id, presence: true

  belongs_to :plant
  belongs_to :seed

  has_many   :production_steps, dependent: :destroy

  after_initialize :defaults
  before_save       :decrement_seed

  def plant_name
    self.plant.nil? ? "" : self.plant.name
  end

  def seed_lot
    self.seed.nil? ? "" : self.seed.lot
  end

  def seed_lots
    self.plant.nil? ? [] : self.plant.seeds
  end

  def first_item_date
    item = self.production_steps.first
    item.nil? ? "" : item.step_date
  end

  def previous
    ProductionCard.where( "id < ?", self.id ).last || ProductionCard.last
  end

  def next
    ProductionCard.where( "id > ?", self.id ).first || ProductionCard.first
  end


  def defaults
    myID = ProductionCard.maximum(:id).nil? ? 1 : ProductionCard.maximum(:id) + 1
    self.card_number ||= "SCP-%05d" % myID
  end

  def decrement_seed
    return if self.seed_decremented
    return if self.seed.nil? || self.seed_quantity.nil? || self.seed_quantity < 1
    seed = self.seed
    seed.remaining -= self.seed_quantity
    seed.save
    self.seed_decremented = true
  end
end

app/controllers/production_cards_controller.rb
class ProductionCardsController < ApplicationController
  before_action :set_production_card, only: [:show, :edit, :update, :destroy]

  # GET /production_cards
  # GET /production_cards.json
  def index
    @production_cards = ProductionCard.all
  end

  # GET /production_cards/1
  # GET /production_cards/1.json
  def show
    @steps = @production_card.production_steps
  end

  # GET /production_cards/new
  def new
    if params[:plant]
      @production_card = ProductionCard.new(plant: Plant.find(params[:plant]))
    elsif params[:seed]
      @production_card = ProductionCard.new(plant: Plant.find(params[:plant]), seed: Seed.find(params[:seed]))
    else
      @production_card = ProductionCard.new
    end
  end

  # GET /production_cards/1/edit
  def edit
  end

  # POST /production_cards
  # POST /production_cards.json
  def create
    @production_card = ProductionCard.new(production_card_params)

    respond_to do |format|
      if @production_card.save
        format.html { redirect_to @production_card, notice: 'Production card was successfully created.' }
        format.json { render :show, status: :created, location: @production_card }
      else
        format.html { render :new }
        format.json { render json: @production_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /production_cards/1
  # PATCH/PUT /production_cards/1.json
  def update
    respond_to do |format|
      if @production_card.update(production_card_params)
        format.html { redirect_to @production_card, notice: 'Production card was successfully updated.' }
        format.json { render :show, status: :ok, location: @production_card }
      else
        format.html { render :edit }
        format.json { render json: @production_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /production_cards/1
  # DELETE /production_cards/1.json
  def destroy
    @production_card.destroy
    respond_to do |format|
      format.html { redirect_to production_cards_url, notice: 'Production card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_production_card
      @production_card = ProductionCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def production_card_params
      params.require(:production_card).permit(:card_number, :plant_id, :seed_id, :seed_quantity, :quantity_needed, :quantity_produced, :seed_decremented, :active)
    end
end

app/helpers/production_cards_helper.rb
module ProductionCardsHelper
end

app/views/production_cards/_cards.html.erb
<tr>
  <td><%= link_to cards.card_number, production_card_path(cards.id) %></td>
  <td><%= cards.plant.name %></td>
  <td><%= cards.seed_lot %></td>
</tr>

app/views/production_cards/_form.html.erb
<%= form_for(@production_card) do |f| %>
  <% if @production_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@production_card.errors.count, "error") %> prohibited this production_card from being saved:</h2>

      <ul>
      <% @production_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :card_number %><br>
    <%= f.text_field :card_number %>
  </div>
  <div class="field">
    <%= f.label :plant_id %><br>
    <%= f.autocomplete_field :plant_name, autocomplete_plant_name_plants_path,
                              id_element: '#plant_id', :update_elements => {} %>
    <%= f.hidden_field :plant_id, id: "plant_id" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/production_cards/edit.html.erb
<h1>Editing Production Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @production_card %> |
<%= link_to 'Back', production_cards_path %>

app/views/production_cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Production Cards</h1>

<table id="production_card_table" class="display">
  <thead>
    <tr>
      <th>Card number</th>
      <th>Plant</th>
      <th>Seed Lot</th>
      <th>Seed Start Date</th>
      <th>Active</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @production_cards.each do |production_card| %>
      <tr>
        <td><%= link_to production_card.card_number, production_card_path(production_card) %></td>
        <td><%= link_to production_card.plant.long_name, production_card.plant %></td>
        <td><%= link_to production_card.seed_lot, production_card.seed %></td>
        <td><%= link_to production_card.first_item_date, production_card.seed %></td>
        <td><%= production_card.active %></td>
        <td><%= link_to 'Edit', edit_production_card_path(production_card) %></td>
        <td><%= link_to 'Destroy', production_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Production card', new_production_card_path %>

app/views/production_cards/new.html.erb
<h1>New Production Card</h1>

<%= render 'form' %>

<%= link_to 'Back', production_cards_path %>

app/views/production_cards/show.html.erb
<div class="no_border">
<p id="notice"><%= notice %></p>
  <% if @production_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@production_card.errors.count, "error") %> prohibited this production_card from being saved:</h2>

      <ul>
      <% @production_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for(@production_card) do |f| %>
  <table class="display subtable" id="prod_card">
    <thead>
      <tr>
        <th colspan="4"><%= "Sun Chaser Production Card #{@production_card.card_number}" %></th>
      </tr>
      <tr>
        <th colspan="4"><h2><%= link_to @production_card.plant.long_name, plant_path(@production_card.plant) %></h2></th>
      </tr>
      <tr>
        <th>Code:</th>
        <th><%= @production_card.plant.germination_code %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= link_to 'Seed', @production_card.seed %></td>
        <td><%= f.collection_select :seed_id, Seed.where(plant: @production_card.plant), :id, :lot_name, prompt: "Select a seed lot." %></td>
        <td><%= f.label :seed_quantity %></td>
        <td><%= f.number_field :seed_quantity %></td>
      </tr>
      <tr>
        <td><%= f.label :quantity_needed %></td>
        <td><%= f.number_field :quantity_needed %></td>
        <td><%= f.label :quantity_produced %></td>
        <td><%= f.number_field :quantity_produced %></td>
      </tr>
      <tr>
        <td>Removed from Seed:</td>
        <td><%= @production_card.seed_decremented %></td>
        <td><%= f.label :active %></td>
        <td><%= f.check_box :active %></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td><%= f.submit %></td>
        <td></td>
      </tr>
    </tbody>
  </table>
  <table class="display subtable" id="prod_steps">
    <thead>
    <tr>
      <th colspan="6"><h2>Production Steps</h2></th>
    </tr>
    <tr>
      <th>Date</th>
      <th>Process</th>
      <th>Description</th>
      <th>Notes</th>
      <th colspan="2">Actions</th>
    </tr>
    </thead>
    <tbody>
    <div id="steps">
      <%= render partial: "production_steps/list", collection: @steps %>
    </div>
    </tbody>
  </table>
<% end %>

<p>
  <% @production_step = ProductionStep.new(production_card: @production_card) %>
  <%= render "production_steps/form" %>
</p>
<%= link_to 'Edit', edit_production_card_path(@production_card) %> |
<%= link_to 'Back', production_cards_path %>
<div class="right">
  <%= link_to 'Prev', production_card_path(@production_card.previous) %> | 
  <%= link_to 'Next', production_card_path(@production_card.next) %>
</div>
</div>