config/routes.rb
Rails.application.routes.draw do
  root to: "plants#index"

  resources :production_steps

  resources :production_cards

  resources :locations do
    get :autocomplete_location_name, on: :collection
  end

  resources :vendors do
    get :autocomplete_vendor_name, on: :collection
  end

  resources :seeds

  resources :plants do
    get :autocomplete_plant_name, on: :collection
  end

  resources :pollinators do
    get :autocomplete_pollinator_name, on: :collection
    member do
      post 'associate'
    end
  end

  resources :common_names

  resources :species

  resources :genus

  resources :families do
    get :autocomplete_family_name, on: :collection
  end

  resources :thermometers

end

app/models/seed.rb
class Seed < ActiveRecord::Base
  validates :plant_id, presence: true
  validates :lot, uniqueness: true
  
  belongs_to :plant
  belongs_to :vendor
  belongs_to :location
  has_many   :production_cards

  after_initialize :defaults

  def plant_name
    self.plant.nil? ? "" : self.plant.name
  end

  def vendor_name
    self.vendor.nil? ? "" : self.vendor.name
  end

  def location_name
    self.location.nil? ? "" : self.location.name
  end

  def lot_name
    self.lot + " " + self.plant_name + " : " + self.remaining.to_s
  end

  def previous
   Seed.where( "id < ?", self.id ).last ||Seed.last
  end

  def next
   Seed.where( "id > ?", self.id ).first ||Seed.first
  end

  def defaults
    myID = Seed.maximum(:id).nil? ? 1 : Seed.maximum(:id) + 1
    self.lot ||= "SCS-%04d" % myID
  end
end

app/controllers/seeds_controller.rb
class SeedsController < ApplicationController
  before_action :set_seed, only: [:show, :edit, :update, :destroy]

  # GET /seeds
  # GET /seeds.json
  def index
    @seeds = Seed.all
  end

  # GET /seeds/1
  # GET /seeds/1.json
  def show
  end

  # GET /seeds/new
  def new
    if params[:plant]
      @seed = Seed.new(plant: Plant.find(params[:plant]))
    else
      @seed = Seed.new
    end
  end

  # GET /seeds/1/edit
  def edit
  end

  # POST /seeds
  # POST /seeds.json
  def create
    @seed = Seed.new(seed_params)

    respond_to do |format|
      if @seed.save
        format.html { redirect_to @seed, notice: 'Seed was successfully created.' }
        format.json { render :show, status: :created, location: @seed }
      else
        format.html { render :new }
        format.json { render json: @seed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seeds/1
  # PATCH/PUT /seeds/1.json
  def update
    respond_to do |format|
      if @seed.update(seed_params)
        format.html { redirect_to @seed, notice: 'Seed was successfully updated.' }
        format.json { render :show, status: :ok, location: @seed }
      else
        format.html { render :edit }
        format.json { render json: @seed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seeds/1
  # DELETE /seeds/1.json
  def destroy
    @seed.destroy
    respond_to do |format|
      format.html { redirect_to seeds_url, notice: 'Seed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seed
      @seed = Seed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seed_params
      params.require(:seed).permit(:lot, :plant_id, :collection_date, :vendor_id, :location_id, :collected_by, :clean, :quantity, :remaining, :notes)
    end
end

app/helpers/seeds_helper.rb
module SeedsHelper
end

app/views/seeds/_form.html.erb
<%= form_for(@seed) do |f| %>
  <% if @seed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seed.errors.count, "error") %> prohibited this seed from being saved:</h2>

      <ul>
      <% @seed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lot %><br>
    <%= f.text_field :lot %>
  </div>
  <div class="field">
    <%= f.label :plant_id %><br>
    <%= f.autocomplete_field :plant_name, autocomplete_plant_name_plants_path,
                              id_element: '#plant_id' %>
    <%= f.hidden_field :plant_id, id: "plant_id" %>
  </div>
  <div class="field">
    <%= f.label :collection_date %><br>
    <%= f.text_field :collection_date, id: "collection_date" %>
  </div>
  <div class="field">
    <%= f.label :vendor_id %><br>
    <%= f.autocomplete_field :vendor_name, autocomplete_vendor_name_vendors_path,
                              id_element: '#vendor_id' %>
    <%= f.hidden_field :vendor_id, id: "vendor_id" %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.autocomplete_field :location_name, autocomplete_location_name_locations_path,
                              id_element: '#location_id' %>
    <%= f.hidden_field :location_id, id: "location_id" %>
  </div>
  <div class="field">
    <%= f.label :collected_by %>/Vendor Lot<br>
    <%= f.text_field :collected_by %>
  </div>
  <div class="field">
    <%= f.label :clean %><br>
    <%= f.check_box :clean %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :remaining %><br>
    <%= f.number_field :remaining %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seeds/_seeds.html.erb
<tr>
  <td><%= link_to seeds.lot, seed_path(seeds.id) %></td>
  <td><%= seeds.collection_date %></td>
  <td><%= seeds.remaining.to_s %></td>
</tr>

app/views/seeds/edit.html.erb
<h1>Editing Seed</h1>

<%= render 'form' %>

<%= link_to 'Show', @seed %> |
<%= link_to 'Back', seeds_path %>

app/views/seeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Seeds</h1>

<table id="seed_table" class="display">
  <thead>
    <tr>
      <th>Lot</th>
      <th>Plant</th>
      <th>Collection date</th>
      <th>Vendor</th>
      <th>Location</th>
      <th>Remaining</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @seeds.each do |seed| %>
      <tr>
        <td><%= link_to seed.lot, seed_path(seed) %></td>
        <td width="40%"><%= link_to seed.plant.long_name, seed.plant %></td>
        <td><%= seed.collection_date %></td>
        <td><%= link_to seed.vendor_name, seed.vendor %></td>
        <td><%= link_to seed.location_name, seed.location %></td>
        <td><%= seed.remaining %></td>
        <td><%= link_to 'Destroy', seed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seed', new_seed_path %>

app/views/seeds/new.html.erb
<h1>New Seed</h1>

<%= render 'form' %>

<%= link_to 'Back', seeds_path %>

app/views/seeds/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Showing Seed Lot <%= @seed.lot %></h1>
<p>
  <strong>Lot:</strong>
  <%= @seed.lot %>
</p>

<p>
  <strong>Plant:</strong>
  <%= link_to @seed.plant.name, @seed.plant %>
</p>

<p>
  <strong>Collection date:</strong>
  <%= @seed.collection_date %>
</p>

<p>
  <strong>Viability (years):</strong>
  <%= @seed.plant.viability %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= link_to @seed.vendor_name, @seed.vendor %>
</p>

<p>
  <strong>Location:</strong>
  <%= link_to @seed.location_name, @seed.location %>
</p>

<p>
  <strong>Collected by/Vendor Lot:</strong>
  <%= @seed.collected_by %>
</p>

<p>
  <strong>Clean:</strong>
  <%= @seed.clean %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @seed.quantity %>
</p>

<p>
  <strong>Remaining:</strong>
  <%= @seed.remaining %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @seed.notes %>
</p>

<%= link_to 'Edit', edit_seed_path(@seed) %> |
<%= link_to 'Back', seeds_path %> | 
<%= link_to 'New Seed', new_seed_path %> | 
<%= link_to 'New P-Card', new_production_card_path(seed: @seed, plant: @seed.plant) %>
<div class="right">
  <%= link_to 'Prev', seed_path(@seed.previous) %> | 
  <%= link_to 'Next', seed_path(@seed.next) %>
</div>

<% if @seed.production_cards.size > 0 %>
<div id="production_cards">
  <table class="display subtable">
    <thead>
      <th colspan="3"><h2><%= "Production Cards for #{@seed.lot}" %></h2></th>
    </thead>
    <tbody>
      <%= render partial: "production_cards/cards", collection:@seed.production_cards %>
    </tbody>
  </table>
</div>
<% end %>