config/routes.rb
Rails.application.routes.draw do
  root to: "plants#index"

  resources :production_steps

  resources :production_cards

  resources :locations do
    get :autocomplete_location_name, on: :collection
  end

  resources :vendors do
    get :autocomplete_vendor_name, on: :collection
  end

  resources :seeds

  resources :plants do
    get :autocomplete_plant_name, on: :collection
  end

  resources :pollinators do
    get :autocomplete_pollinator_name, on: :collection
    member do
      post 'associate'
    end
  end

  resources :common_names

  resources :species

  resources :genus

  resources :families do
    get :autocomplete_family_name, on: :collection
  end

  resources :thermometers

end

app/models/plant.rb
class Plant < ActiveRecord::Base
  validates :name, presence: true
  validates :genus_id, presence: true
  validates :species_id, presence: true

  before_validation :set_other_params

  has_many   :seeds
  has_many   :locations, through: :seeds
  has_many   :vendors,   through: :seeds
  has_many   :production_cards
  has_and_belongs_to_many :pollinators
  
  belongs_to :family
  belongs_to :genus
  belongs_to :species

  default_scope { order('name ASC') }

  def long_name
    "#{self.name} | #{self.common_name}"
  end

  def family_name
    self.family.nil? ? "" : self.family.name
  end

  def genus_name
    self.genus.nil? ? "" : self.genus.name
  end

  def species_name
    self.species.nil? ? "" : self.species.name
  end

  def seeds_on_hand
    self.seeds.sum(:remaining)
  end

  def previous
    Plant.where( "name < ?", self.name ).last || Plant.last
  end

  def next
    Plant.where( "name > ?", self.name ).first || Plant.first
  end

  def usda_link
    symbol = (self.genus.name + "+" + self.species.name)
    link = "http://plants.usda.gov/java/nameSearch?keywordquery=#{symbol}&mode=sciname"
  end

  private

  def set_other_params
    gs = self.name.split(" ")
    if self.genus.nil?
      unless gs[0].nil?
        genus = Genus.where(name: gs[0]).first_or_create
        self.genus = genus
        genus.save
      end
    end
    if self.species.nil?
      unless gs[1].nil?
        species = Species.where(name: gs[1]).first_or_create
        self.species = species
        species.save
      end
    end
  end

end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit, :update, :destroy]
  autocomplete :plant, :name, full: true

  # GET /plants
  # GET /plants.json
  def index
    @plants = Plant.all
  end

  # GET /plants/1
  # GET /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
    @show_selectors = false
  end

  # GET /plants/1/edit
  def edit
    @show_selectors = true
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1
  # PATCH/PUT /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: 'Plant was successfully updated.' }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url, notice: 'Plant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plant_params
      if params[:plant]
        params.require(:plant).permit(:name, :family_id, :genus_id, :species_id, :common_name, :description, :germination_code, :series, :notes, :viability)
      else
        params.permit(:name, :family_id, :genus_id, :species_id, :common_name, :description, :germination_code, :series, :notes, :viability)
      end
    end
end

app/helpers/plants_helper.rb
module PlantsHelper

  def plant_family_path(plant)
    plant.family.nil? ? "#" : family_path(plant.family)
  end
  
end

app/views/plants/_form.html.erb
<%= form_for(@plant) do |f| %>
  <% if @plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% @plant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :family_id %><br>
    <%= f.autocomplete_field :family_name, autocomplete_family_name_families_path,
                              id_element: '#fam_id' %>
    <%= f.hidden_field :family_id, id: "fam_id" %>
  </div>
  <% if @show_selectors == true %>
  <div class="field">
    <%= f.label :genus_id %><br>
    <%= f.collection_select :genus_id, Genus.all, :id, :name, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :species_id %><br>
    <%= f.collection_select :species_id, Species.all, :id, :name, prompt: true %>
  </div>
  <% end %>
  <div class="field">
    <%= f.label :series %><br>
    <%= f.text_field :series %>
  </div>
  <div class="field">
    <%= f.label :common_name %><br>
    <%= f.text_field :common_name %>
  </div>
  <div class="field">
    <%= f.label :germination_code %><br>
    <%= f.text_field :germination_code %>
  </div>
  <div class="field">
  <%= f.label :viability %><br>
  <%= f.text_field :viability %>
</div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
  <%= f.label :notes %><br>
  <%= f.text_area :notes %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plants/_plant.html.erb
<tr>
  <td><%= link_to plant.name, plant_path(plant) %></td>
  <td><%= link_to plant.family_name, plant_family_path(plant) %></td>
  <td><%= link_to plant.genus_name, plant.genus %></td>
  <td><%= link_to plant.species_name, plant.species %></td>
  <td><%= plant.series %></td>
  <td><%= plant.common_name %></td>
</tr>

app/views/plants/edit.html.erb
<h1>Editing Plant</h1>

<%= render 'form' %>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

app/views/plants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Plants</h1>

<table id="plant_table" class="display">
  <thead>
    <tr>
      <th>Name</th>
      <th>Family</th>
      <th>Genus</th>
      <th>Species</th>
      <th>Series</th>
      <th>Common name</th>
    </tr>
  </thead>

  <tbody>
    <%= render partial: "plants/plant", collection: @plants %>
  </tbody>
</table>

<br>

<%= link_to 'New Plant', new_plant_path %>

app/views/plants/new.html.erb
<h1>New Plant</h1>

<%= render 'form' %>

<%= link_to 'Back', plants_path %>

app/views/plants/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Showing Plant <%= @plant.name %></h1>
<p>
  <strong>Name:</strong>
  <%= @plant.name %>
</p>

<p>
  <strong>Family:</strong>
  <%= link_to @plant.family_name, plant_family_path(@plant)  %>
</p>

<p>
  <strong>Genus:</strong>
  <%= link_to @plant.genus_name, @plant.genus %>
</p>

<p>
  <strong>Species:</strong>
  <%= link_to @plant.species_name, @plant.species %>
</p>

<p>
  <strong>Common name:</strong>
  <%= @plant.common_name %>
</p>

<p>
  <strong>Series:</strong>
  <%= @plant.series %>
</p>

<p>
  <strong>Germination Code:</strong>
  <%= @plant.germination_code %>
</p>

<p>
  <strong>Years Viable:</strong>
  <%= @plant.viability %>
</p>

<p>
  <strong>Description:</strong>
  <%= @plant.description %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @plant.notes %>
</p>

<p>
  <strong>Seeds On Hand:</strong>
  <%= @plant.seeds_on_hand %>
</p>

<p>
  <strong>USDA LINK:</strong> 
  <%= link_to @plant.name, @plant.usda_link, target: "_blank" %>
</p>

<%= link_to 'Edit', edit_plant_path(@plant) %> |
<%= link_to 'Back', plants_path %> |
<%= link_to 'Destroy', @plant, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Get Seed', new_seed_path(plant: @plant) %> | 
<%= link_to 'New P-Card', new_production_card_path(plant: @plant) %>
<div class="right">
  <%= link_to 'Prev', plant_path(@plant.previous) %> | 
  <%= link_to 'Next', plant_path(@plant.next) %>
</div>

<% if @plant.pollinators.size > 0 %>
<div id="pollinators">
  <table class="display subtable">
    <thead>
      <th colspan="5"><h2><%= "Pollinators that visit #{@plant.name} in the wild" %></h2></th>
    </thead>
    <tbody>
      <%= render partial: "pollinators/pollinator", collection: @plant.pollinators.uniq %>
    </tbody>
  </table>
</div>
<% end %>

<% if @plant.locations.size > 0 %>
<div id="locations">
  <table class="display subtable">
    <thead>
      <th colspan="4"><h2><%= "Places to find #{@plant.name} in the wild" %></h2></th>
    </thead>
    <tbody>
      <%= render partial: "locations/location", collection: @plant.locations.uniq %>
    </tbody>
  </table>
</div>
<% end %>

<% if @plant.production_cards.size > 0 %>
<div id="production_cards">
  <table class="display subtable">
    <thead>
      <th colspan="3"><h2><%= "Production Cards for #{@plant.name}" %></h2></th>
    </thead>
    <tbody>
      <%= render partial: "production_cards/cards", collection:@plant.production_cards %>
    </tbody>
  </table>
</div>
<% end %>

<% if @plant.seeds.size > 0 %>
<div id="seeds">
  <table class="display subtable">
    <thead>
      <th colspan="3"><h2><%= "Seed Lots for #{@plant.name}" %></h2></th>
    </thead>
    <tbody>
      <%= render partial: "seeds/seeds", collection:@plant.seeds %>
    </tbody>
  </table>
</div>
<% end %>