config/routes.rb
Rails.application.routes.draw do
  root to: "plants#index"

  resources :production_steps

  resources :production_cards

  resources :locations do
    get :autocomplete_location_name, on: :collection
  end

  resources :vendors do
    get :autocomplete_vendor_name, on: :collection
  end

  resources :seeds

  resources :plants do
    get :autocomplete_plant_name, on: :collection
  end

  resources :pollinators do
    get :autocomplete_pollinator_name, on: :collection
    member do
      post 'associate'
    end
  end

  resources :common_names

  resources :species

  resources :genus

  resources :families do
    get :autocomplete_family_name, on: :collection
  end

  resources :thermometers

end

app/models/genus.rb
class Genus < ActiveRecord::Base
  validates :name, length: { minimum: 3 }
  has_many :plants

  default_scope { order('name ASC') }
  
  def previous
   Genus.where( "name < ?", self.name ).last ||Genus.last
  end

  def next
   Genus.where( "name > ?", self.name ).first ||Genus.first
  end

end

app/controllers/genus_controller.rb
class GenusController < ApplicationController
  before_action :set_genus, only: [:show, :edit, :update, :destroy]

  # GET /genus
  # GET /genus.json
  def index
    @genus = Genus.all
  end

  # GET /genus/1
  # GET /genus/1.json
  def show
  end

  # GET /genus/new
  def new
    @genus = Genus.new
  end

  # GET /genus/1/edit
  def edit
  end

  # POST /genus
  # POST /genus.json
  def create
    @genus = Genus.new(genus_params)

    respond_to do |format|
      if @genus.save
        format.html { redirect_to @genus, notice: 'Genus was successfully created.' }
        format.json { render :show, status: :created, location: @genus }
      else
        format.html { render :new }
        format.json { render json: @genus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genus/1
  # PATCH/PUT /genus/1.json
  def update
    respond_to do |format|
      if @genus.update(genus_params)
        format.html { redirect_to @genus, notice: 'Genus was successfully updated.' }
        format.json { render :show, status: :ok, location: @genus }
      else
        format.html { render :edit }
        format.json { render json: @genus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genus/1
  # DELETE /genus/1.json
  def destroy
    @genus.destroy
    respond_to do |format|
      format.html { redirect_to genus_index_url, notice: 'Genus was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genus
      @genus = Genus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genus_params
      params.require(:genus).permit(:name, :common_name, :description)
    end
end

app/helpers/genus_helper.rb
module GenusHelper
end

app/views/genus/_form.html.erb
<%= form_for(@genus) do |f| %>
  <% if @genus.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genus.errors.count, "error") %> prohibited this genus from being saved:</h2>

      <ul>
      <% @genus.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :common_name %><br>
    <%= f.text_field :common_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genus/edit.html.erb
<h1>Editing Genus</h1>

<%= render 'form' %>

<%= link_to 'Show', @genus %> |
<%= link_to 'Back', genus_index_path %>

app/views/genus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Genus</h1>

<table id="genus_table" class="display">
  <thead>
    <tr>
      <th>Name</th>
      <th>Common name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @genus.each do |genus| %>
      <tr>
        <td><%= genus.name %></td>
        <td><%= genus.common_name %></td>
        <td><%= genus.description %></td>
        <td><%= link_to 'Show', genus %></td>
        <td><%= link_to 'Edit', edit_genus_path(genus) %></td>
        <td><%= link_to 'Destroy', genus, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Genus', new_genus_path %>

app/views/genus/new.html.erb
<h1>New Genus</h1>

<%= render 'form' %>

<%= link_to 'Back', genus_index_path %>

app/views/genus/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Showing Genus <%= @genus.name %></h1>
<p>
  <strong>Name:</strong>
  <%= @genus.name %>
</p>

<p>
  <strong>Common name:</strong>
  <%= @genus.common_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @genus.description %>
</p>

<%= link_to 'Edit', edit_genus_path(@genus) %> |
<%= link_to 'Back', genus_index_path %>
<div class="right">
  <%= link_to 'Prev', genus_path(@genus.previous) %> | 
  <%= link_to 'Next', genus_path(@genus.next) %>
</div>

<div id="plants">
  <table class="display subtable">
    <thead>
      <th colspan="5"><%= "Plants with Genus #{@genus.name}" %></th>
    </thead>
    <tbody>
      <%= render partial: "plants/plant", collection: @genus.plants.uniq %>
    </tbody>
  </table>
</div>